language: c
sudo: required
install:
  # the cmocka package coming with trusty is not up to date
  - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar -xf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug .. && make && sudo make install
  - cd ../..
  - rm -rf cmocka-1.1.0
script:
  - cd tests && mkdir build && cd build && cmake .. && make && make test
